# Generated by Django 2.0.4 on 2018-05-04 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='broker_app.Survey'),
            preserve_default=False,
        ),
    ]
