# Generated by Django 2.0.4 on 2018-04-19 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broker_app', '0002_survey_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_tenant', models.CharField(max_length=255)),
                ('type_of_tenant', models.CharField(max_length=255)),
                ('building_class', models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('Any', 'Any')], default='Any', max_length=3)),
                ('minimum_rsf', models.FloatField()),
                ('maximum_rsf', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TourBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.CharField(max_length=255)),
                ('tour_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
