# Generated by Django 2.0.4 on 2018-05-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0002_mediaupload_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='upload_type',
            field=models.CharField(choices=[('Floorplan', 'Floorplan'), ('Image', 'Image')], default='Image', max_length=15),
        ),
    ]
