# Generated by Django 2.0.4 on 2018-04-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0003_executivesummary_requirement_tourbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbook',
            name='tour_date',
            field=models.DateField(),
        ),
    ]
