# Generated by Django 2.0.4 on 2018-05-02 21:59

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0004_auto_20180418_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='annual_increase_in_net_rental_rate_USD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='building_avg_floor_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='building_capital_improvements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='building_number_of_floors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='building_reserved_parking_rates_USD_per_DAY',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='building_reserved_parking_ratio',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='survey',
            name='building_size_RSF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='building_unreserved_parking_rates_USD_per_DAY',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='building_unreserved_parking_ratio',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='survey',
            name='estimated_yearly_operating_expenses_USD',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='quoted_free_rent_basis',
            field=models.CharField(choices=[('Gross', 'Gross'), ('Net', 'Net')], default='Gross', max_length=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='quoted_free_rent_months_CNT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='quoted_improvement_allowance_USD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='quoted_net_rental_rate_USD_per_RSF',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='subject_space_existing_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='subject_space_floors',
            field=models.CharField(default='0', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AddField(
            model_name='survey',
            name='subject_space_former_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='subject_space_size_RSF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='supplemental_garage_reserved_parking_rates_USD_per_DAY',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='supplemental_garage_reserved_parking_ratio',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='survey',
            name='supplemental_garage_unreserved_parking_rates_USD_per_DAY',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='supplemental_garage_unreserved_parking_ratio',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='tourbook',
            name='surveys',
            field=models.ManyToManyField(to='broker_app.Survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='building_address',
            field=models.CharField(default='default_address', max_length=255),
        ),
        migrations.AlterField(
            model_name='survey',
            name='building_name',
            field=models.CharField(default='default_building', max_length=255),
        ),
        migrations.AlterField(
            model_name='survey',
            name='zipcode',
            field=models.CharField(default='77019', max_length=10),
        ),
    ]
