# Generated by Django 2.0.4 on 2018-05-03 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker_app', '0006_mediaupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='building_class',
        ),
        migrations.AddField(
            model_name='requirement',
            name='building_class_A',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='requirement',
            name='building_class_B',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='requirement',
            name='building_class_C',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='requirement',
            name='commencement_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='desired_percentage_offices_PCT',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1.1), django.core.validators.MinValueValidator(-0.1)]),
        ),
        migrations.AddField(
            model_name='requirement',
            name='lease_or_purchase',
            field=models.CharField(choices=[('Lease', 'Lease'), ('Purchase', 'Purchase')], default='Lease', max_length=10),
        ),
        migrations.AddField(
            model_name='requirement',
            name='needs_furniture',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='requirement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='submarket_A',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='requirement',
            name='submarket_B',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='requirement',
            name='submarket_C',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='requirement',
            name='submarket_D',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='requirement',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='broker_app.Survey'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='term_length_YRS',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='maximum_rsf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='minimum_rsf',
            field=models.FloatField(default=0),
        ),
    ]
